import '../models/product.dart';

List<Product> products = [
  const Product(
    name: "Strawberries",
    description: "Strawberries are nutritious",
    image: 'assets/images/straw.jpg',
    price: 25.0,
    unit: "Kg",
    rating: 4.35,
    category: "Fruits",
  ),
  const Product(
    name: "Oranges",
    description: "Oranges are nutritious",
    image: 'assets/images/orange.jpg',
    price: 15.0,
    unit: "Kg",
    rating: 3.45,
    category: "Fruits",
  ),
  const Product(
    name: "Potatoes",
    description: "Potatoes are nutritious",
    image: 'assets/images/potato.jpg',
    price: 12.0,
    unit: "Kg",
    rating: 8.45,
    category: "Vegetables",
  ),
  const Product(
    name: "Tomatoes",
    description: "Tomatoes are nutritious",
    image: 'assets/images/tomato.jpg',
    price: 10.0,
    unit: "Kg",
    rating: 5.0,
    category: "Vegetables",
  ),
  const Product(
    name: "Carrots",
    description: "Carrots are nutritious",
    image: 'assets/images/carrot.jpg',
    price: 10.0,
    unit: "Kg",
    rating: 6.1,
    category: "Vegetables",
  ),
  const Product(
    name: "Lemons",
    description: "Lemons are nutritious",
    image: 'assets/images/lemon.jpg',
    price: 45.0,
    unit: "Kg",
    rating: 4.0,
    category: "Fruits",
  ),
  const Product(
    name: "Watermelons",
    description: "Watermelons are nutritious",
    image: 'assets/images/watermelon.jpg',
    price: 25.0,
    unit: "Kg",
    rating: 6.5,
    category: "Fruits",
  ),
  const Product(
    name: "Grapes",
    description: "Grapes are nutritious",
    image: 'assets/images/grappe.jpg',
    price: 40.0,
    unit: "Kg",
    rating: 7.0,
    category: "Fruits",
  ),
];
